import Foundation

struct Track: Codable, Identifiable, Hashable {
    let id: String
    let title: String
    let duration: Int
    let streamUrl: String?
    let playCount: Int?
    let artwork: Artwork?
    let user: User?
    let genre: String?
    let mood: String?
    let tags: String?
    let releaseDate: String?
    let description: String?
    /// Non-nil when this track was generated by AI trained on another Audius artist.
    /// The value is the Audius user ID of the artist whose music was used for training.
    let aiAttributionUserId: String?

    /// True if any tag or the AI attribution field indicates AI involvement.
    var isAiAttributed: Bool {
        if aiAttributionUserId != nil { return true }
        let aiKeywords = ["ai", "ai-generated", "artificial intelligence", "ai generated", "aimusic"]
        let tagList = (tags ?? "").lowercased().split(separator: ",").map { $0.trimmingCharacters(in: .whitespaces) }
        return tagList.contains(where: { aiKeywords.contains($0) })
    }

    var formattedDuration: String {
        let minutes = duration / 60
        let seconds = duration % 60
        return String(format: "%d:%02d", minutes, seconds)
    }

    var formattedPlayCount: String? {
        guard let count = playCount else { return nil }
        if count >= 1_000_000 {
            return String(format: "%.1fM", Double(count) / 1_000_000.0)
        } else if count >= 1_000 {
            return String(format: "%.1fK", Double(count) / 1_000.0)
        } else {
            return "\(count)"
        }
    }

    func hash(into hasher: inout Hasher) {
        hasher.combine(id)
    }

    static func == (lhs: Track, rhs: Track) -> Bool {
        lhs.id == rhs.id
    }
}

struct Artwork: Codable {
    private enum CodingKeys: String, CodingKey {
        case small = "150x150"
        case medium = "480x480"
        case large = "1000x1000"
        case mirrors
    }

    let small: String?
    let medium: String?
    let large: String?
    let mirrors: [String]?

    func url(size: ArtworkSize = .large) -> String? {
        switch size {
        case .small:
            return small
        case .medium:
            return medium
        case .large:
            return large
        }
    }

    func mirrorUrls(for size: ArtworkSize = .large) -> [String] {
        guard let baseUrl = url(size: size),
              let mirrors = mirrors else {
            return []
        }
        guard let baseURL = URL(string: baseUrl) else { return [] }
        
        return mirrors.compactMap { mirror in
            guard let mirrorURL = URL(string: mirror),
                  mirrorURL.scheme?.lowercased() == "https" else { return nil }
            var components = URLComponents(url: baseURL, resolvingAgainstBaseURL: false)
            components?.scheme = mirrorURL.scheme
            components?.host = mirrorURL.host
            return components?.url?.absoluteString
        }
    }
}

enum ArtworkSize {
    case small, medium, large
}

struct User: Codable, Identifiable, Hashable {
    let id: String
    let handle: String
    let name: String
    let bio: String?
    let profilePicture: Artwork?
    let followerCount: Int?
    let trackCount: Int?
    let isVerified: Bool?
    /// Whether this artist has opted in to allowing AI to train on their music.
    let allowAiAttribution: Bool?

    func hash(into hasher: inout Hasher) {
        hasher.combine(id)
    }

    static func == (lhs: User, rhs: User) -> Bool {
        lhs.id == rhs.id
    }
}

struct Playlist: Codable, Identifiable, Hashable {
    let id: String
    let name: String
    let description: String?
    let artwork: Artwork?
    let user: User?
    let trackCount: Int?
    let duration: Int?

    func hash(into hasher: inout Hasher) {
        hasher.combine(id)
    }

    static func == (lhs: Playlist, rhs: Playlist) -> Bool {
        lhs.id == rhs.id
    }
}

struct TrackListResponse: Codable {
    let data: [Track]
}

struct TrackResponse: Codable {
    let data: Track
}

struct UserResponse: Codable {
    let data: User
}

struct UserListResponse: Codable {
    let data: [User]
}

struct PlaylistResponse: Codable {
    let data: Playlist
}

struct PlaylistListResponse: Codable {
    let data: [Playlist]
}

/// Activity item returned by the /users/{id}/favorites endpoint.
struct FavoriteActivity: Codable {
    let favoriteItemId: Int?
    let favoriteType: String?
    let createdAt: String?
}

struct FavoriteActivityResponse: Codable {
    let data: [FavoriteActivity]
}
